[package]
name = "precompile"
version = "0.1.0"
authors = ["Cody Joseph Krainock <codykrainock@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
log = "0.4.14"
rand = { version = "0.8.4", default-features = false, features = ["std", "std_rng"] }
