[package]
name = "common"
version = "0.1.0"
authors = ["Cody Joseph Krainock <codykrainock@gmail.com>"]
edition = "2018"

[dependencies]
regex = { version = "1.5", default-features = false, features = ["std"] }
once_cell = "1.19"
